const AppState = {
    dataset: [],
    selectedDateTime: null,
    minimoContractual: 34,
    trendChart: null,
    pointChartData: new WeakMap(),
    normalDownstream: new WeakMap(),
    measurementContext: null,
    sharedStateReady: false,
    sharedStateBusy: false,
    sharedStateVersion: null,
    sharedStateError: '',
    simulationTime: Date.now(),
    selectedMeasurementPoint: null,
    highlightPipelinePoint: null,
};
